### ISSUE TITLE
\Laminas\Form\View\Helper\FormSelect does not allow class attribute for <option>s

### ISSUE THREAD

**Issue by mattfletcher** [laminas/laminas-form#239] opened 2023-08-15 09:32 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.1.x-dev

#### Summary

It is not possible to set a class="" attribute on a <option> tag in a form.

#### Current behavior

The class attributes specified on the valueOptions array are stripped out.

#### How to reproduce

```
$valueOptions = [];
foreach (countries() as $country) {
    $valueOptions[] = [
        'name'  => $country['name'],
        'class' => 'fi fi-' . strtolower($country['iso_3166_1_alpha2']),
        'value' => $country['iso_3166_1_alpha2'],
        'label' => $country['name'] . ' (+' . $country['calling_code'] . ')',
    ];
}

usort($valueOptions, static fn($a, $b) => $a['name'] <=> $b['name']);

$element = new Select(self::COUNTRY_CALLING_CODE);
$element->setLabel('Country calling code');
$element->setValueOptions($valueOptions);
```

#### Expected behavior

Each option would have a class attribute of "fi fi-gb" (etc)

**Comment by Xerkus** [comment] 2023-08-15 17:55
`class` is an attribute, not an option:

```php
$valueOptions = [];
foreach (countries() as $country) {
    $valueOptions[] = [
        'name'  => $country['name'],
        'attributes' => [
            'class' => 'fi fi-' . strtolower($country['iso_3166_1_alpha2']),
        ],
        'value' => $country['iso_3166_1_alpha2'],
        'label' => $country['name'] . ' (+' . $country['calling_code'] . ')',
    ];
}

usort($valueOptions, static fn($a, $b) => $a['name'] <=> $b['name']);

$element = new Select(self::COUNTRY_CALLING_CODE);
$element->setLabel('Country calling code');
$element->setValueOptions($valueOptions);
```

There is a test asserting class attribute is utilized, so marking this as not a bug:

https://github.com/laminas/laminas-form/blob/c6100a664879b6f5638b0fae0c844051f2159902/test/View/Helper/FormSelectTest.php#L71C98-L71C98

**Closed as not planned by Xerkus** 2023-08-15 17:55 UTC
Labels: Bug, Invalid

**Comment by froschdesign** [comment] 2023-08-16 03:35
This can also be found in the documentation: 

> Attributes on the options are supported by providing the options as a specification array instead of key-value pairs: 

https://docs.laminas.dev/laminas-form/v3/element/select/#basic-usage
