### ISSUE TITLE
Form element remove enhancement 

### ISSUE THREAD

**Issue by mdhia** [laminas/laminas-form#76] opened 2020-10-27 13:01 UTC
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

After remove a form element, the input filter still exists. It would be better if $form->remove(...) automatically delete the InputFilter.

**Comment by froschdesign** [comment] 2020-10-27 13:05
Duplicate of #21

**Closed as completed by froschdesign** 2020-10-27 13:05 UTC
Labels: Duplicate
